//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::chunk::Entity as Chunk;
pub use super::kg_edge::Entity as KgEdge;
pub use super::kg_entity::Entity as KgEntity;
pub use super::pass_key::Entity as PassKey;
pub use super::space::Entity as Space;
pub use super::space_index_status::Entity as SpaceIndexStatus;
pub use super::user::Entity as User;
