//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "space")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub key: String,
    /// Human-readable name for the space (derived from directory path or user-specified)
    pub name: Option<String>,
    pub location: String,
    pub time_created: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::space_index_status::Entity")]
    SpaceIndexStatus,
}

impl Related<super::space_index_status::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SpaceIndexStatus.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
